(function(root){
'use strict';
const categories={river:{en:'Rivers',bn:'নদী',color:'#277eaa',words:['river','rivers','নদী','নদীঘেরা']},waterfall:{en:'Waterfalls',bn:'জলপ্রপাত',color:'#3c8691',words:['waterfall','waterfalls','জলপ্রপাত']},beach:{en:'Beaches',bn:'সমুদ্রসৈকত',color:'#24759b',words:['beach','beaches','coast','coastal','sea','seaside','সৈকত','সমুদ্র','সমুদ্রসৈকত','উপকূল']},forest:{en:'Forests',bn:'বন',color:'#25764c',words:['forest','forests','mangrove','wildlife','বন','জঙ্গল','বন্যপ্রাণী','ম্যানগ্রোভ']},tea:{en:'Tea gardens',bn:'চা-বাগান',color:'#76922c',words:['tea','garden','gardens','চা','চাবাগান','চা-বাগান']},lake:{en:'Lakes',bn:'হ্রদ',color:'#168a94',words:['lake','lakes','হ্রদ','লেক']},hill:{en:'Hills',bn:'পাহাড়',color:'#95623e',words:['hill','hills','mountain','mountains','পাহাড়','পাহাড়','পাহাড়ি']},history:{en:'History',bn:'ঐতিহাসিক স্থান',color:'#a75940',words:['historic','historical','history','heritage','ancient','ঐতিহাসিক','ইতিহাস','প্রাচীন']},landmark:{en:'Landmarks',bn:'জাতীয় নিদর্শন',color:'#895b95',words:['landmark','landmarks','national','memorial','monument','monuments','জাতীয়','জাতীয়','স্মৃতিসৌধ','নিদর্শন','স্মৃতিস্তম্ভ']}};
const regions={Dhaka:{bn:'ঢাকা',aliases:['dhaka','ঢাকা','ঢাকার'],centre:[23.8103,90.4125]},Chattogram:{bn:'চট্টগ্রাম',aliases:['chattogram','chittagong','চট্টগ্রাম','চট্টগ্রামের'],centre:[22.3569,91.7832]},Khulna:{bn:'খুলনা',aliases:['khulna','খুলনা','খুলনার'],centre:[22.8456,89.5403]},Sylhet:{bn:'সিলেট',aliases:['sylhet','সিলেট','সিলেটের'],centre:[24.8949,91.8687]},Rajshahi:{bn:'রাজশাহী',aliases:['rajshahi','রাজশাহী','রাজশাহীর'],centre:[24.3745,88.6042]},Barishal:{bn:'বরিশাল',aliases:['barishal','barisal','বরিশাল'],centre:[22.701,90.3535]},Rangpur:{bn:'রংপুর',aliases:['rangpur','রংপুর'],centre:[25.7439,89.2752]},Mymensingh:{bn:'ময়মনসিংহ',aliases:['mymensingh','ময়মনসিংহ','ময়মনসিংহ'],centre:[24.7471,90.4203]}};
function normalize(s){return String(s||'').toLowerCase().normalize('NFC').replace(/[’']/g,'').replace(/[^\p{L}\p{N}\p{M}\s-]/gu,' ').replace(/\s+/g,' ').trim()}
function distance(a,b){const rad=x=>x*Math.PI/180;const x=rad(b[0]-a[0]),y=rad(b[1]-a[1]);const v=Math.sin(x/2)**2+Math.cos(rad(a[0]))*Math.cos(rad(b[0]))*Math.sin(y/2)**2;return 6371*2*Math.atan2(Math.sqrt(v),Math.sqrt(1-v))}
function editDistance(a,b){const v=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let prev=v[0];v[0]=i;for(let j=1;j<=b.length;j++){const old=v[j];v[j]=Math.min(v[j]+1,v[j-1]+1,prev+(a[i-1]!==b[j-1]));prev=old}}return v[b.length]}
const stop=new Set(['a','an','the','in','of','at','and','or','with','for','to','me','my','find','show','visit','explore','places','place','spots','spot','destinations','destination','near','nearby','around','close','best','famous','bangladesh','বাংলাদেশ','এর','এ','ও','এবং','বা','কাছে','কাছাকাছি','আশেপাশে','দেখাও','দেখান','খুঁজুন','স্থান','জায়গা','জায়গা','বিখ্যাত']);
function search(data,options={}){const q=normalize(options.query),tokens=q.split(' ').filter(Boolean);const types=[];const consumed=new Set();for(const [key,c]of Object.entries(categories)){for(const w of c.words){if(tokens.includes(w)){types.push(key);consumed.add(w)}}}let region='';for(const [key,r]of Object.entries(regions)){for(const a of r.aliases){if(tokens.includes(a)){region=key;consumed.add(a)}}}const near=tokens.some(x=>['near','nearby','around','close','কাছে','কাছাকাছি','আশেপাশে'].includes(x));let origin=options.origin||null;if(near&&region)origin=regions[region].centre;const unesco=options.unesco||tokens.some(x=>['unesco','ইউনেসকো'].includes(x));const remaining=tokens.filter(t=>!stop.has(t)&&!consumed.has(t)&&!['unesco','ইউনেসকো'].includes(t));let results=data.filter(d=>(!options.region||d.region===options.region)&&(!region||near||d.region===region)&&(!options.category||d.category===options.category)&&(!types.length||types.includes(d.category)||(d.category==='lake'&&types.includes('hill')))&&(!unesco||d.unesco));results=results.map(d=>{const hay=normalize([d.name.en,d.name.bn,d.district.en,d.district.bn,d.description.en,d.description.bn,...d.aliases].join(' '));const names=normalize([d.name.en,d.name.bn,...d.aliases].join(' ')).split(' ');let score=0;for(const t of remaining){if(hay.includes(t))score+=10;else if(t.length>=4&&names.some(w=>Math.abs(w.length-t.length)<=1&&editDistance(w,t)<=1))score+=5;else return null}const km=origin?distance(origin,[d.lat,d.lng]):null;if(near&&origin&&km>150)return null;return {...d,score,km}}).filter(Boolean);if(options.sort==='name')results.sort((a,b)=>a.name[options.lang||'en'].localeCompare(b.name[options.lang||'en']));else if(origin&&(near||options.sort==='distance'))results.sort((a,b)=>a.km-b.km);else results.sort((a,b)=>b.score-a.score);return{results,origin,near,region,types:[...new Set(types)],unesco,query:q}}
root.BDSearch={search,distance,normalize,categories,regions};
})(typeof window!=='undefined'?window:globalThis);
